#!/bin/bash

echo "🚀 Deploying URL Shortener to Production"
echo "========================================"

echo "📋 Pre-deployment Checklist:"
echo "✅ MongoDB connection fixed"
echo "✅ Production config optimized"
echo "✅ Vercel.json configured"
echo "✅ Environment variables ready"

echo ""
echo "🔧 Next Steps:"
echo "1. Push to GitHub:"
echo "   git remote add origin https://github.com/YOUR-USERNAME/URL-Shortener.git"
echo "   git push -u origin main"
echo ""
echo "2. Deploy Backend to Vercel:"
echo "   cd backend"
echo "   vercel --prod"
echo ""
echo "3. Set Environment Variables in Vercel:"
echo "   - MONGO_URI (your production MongoDB URI)"
echo "   - JWT_SECRET (secure random string)"
echo "   - NODE_ENV=production"
echo "   - FRONTEND_URL (your frontend domain)"
echo "   - SMTP credentials for email"
echo ""
echo "4. Deploy Frontend to Vercel:"
echo "   cd frontend"
echo "   vercel --prod"
echo ""
echo "5. Update CORS settings in backend with frontend URL"

echo ""
echo "🌐 Your app will be live at:"
echo "Backend: https://your-backend-domain.vercel.app"
echo "Frontend: https://your-frontend-domain.vercel.app"
